### ISSUE TITLE
Add to f-droid

### ISSUE THREAD

**Issue by alex9099** [tejado/Authorizer#2]
Hi, any ideas into adding this project to f-droid?

**Comment by tejado** [comment]
I found it already in a f-droid user repository: https://android.izzysoft.de/repo/apk/net.tjado.passwdsafe
But I will check what's necessary to do to add it to the official one :)

**Comment by IzzySoft** [comment]
It should be sufficient to [open a corresponding issue](https://gitlab.com/fdroid/rfp/issues/275) with their RFP (Request For Packaging) repo. I see no show-stopper from a quick glance at your gradle file and my library analyzer. Of course I'm happily keeping the app in my repo – but it's always a good idea to go for the official one. No conflict to have it in both, but the official one of course has a much better reputation than mine – not at last because of much stronger rules. Still, my repo served as "jumping point" for more than one app :wink:

PS: Please follow the above link in case the F-Droid team requires some feedback, @tejado  :stuck_out_tongue_winking_eye:

**Comment by IzzySoft** [comment]
@tejado @alex9099 [Done](https://gitlab.com/fdroid/fdroiddata/commit/176add0922c1064c2c1cc031684b491b1fa5af2a). Should show up on F-Droid within a few days (don't panic before day 5 :wink: It first needs to be build from source, then the repo itself needs to be updated – the process usually requires 2..5 days in my experience.

Enjoy!

**Comment by alex9099** [comment]
Thank you, this can be closed, i think :)

**Comment by tejado** [comment]
:o awesome! Thanks a lot for this!
