### ISSUE TITLE
No way to delete password records

### ISSUE THREAD

**Issue by Alexander-Shukaev** [tejado/Authorizer#40]
Hi, maybe I missed something, but currently there is no button to delete a single password record, only editing is possible.

**Comment by tejado** [comment]
@Alexander-Shukaev 
You can but it seems that there is a GUI issue in which the menu icon on the top-right is not shown in the password-entry fragment. But the menu is still clickable: so on the top right, next to the plus, there is some space where you open the password-entry menu. 
Of course, this needs to be fixed. Feel free to provide a PR otherwise I will need to find some time to fix it.

**Comment by tejado** [comment]
Fixed by PR #48
