### ISSUE TITLE
feature request: pass integration

### ISSUE THREAD

**Issue by alex9099** [tejado/Authorizer#6]
Hi, finally authorizer is on f droid :) 

It would be nice to have pass integration since this is a "standart" format for password storing (with gpg encryptation) and that works with git 

Here is pass website for reference : https://www.passwordstore.org/

Also there is a project here on github that already integrates this format which i dont remeber the name

**Comment by jmichael2497** [comment]
the commonly recommended self managed systems seem to be "pass" "keepass" "pwsafe" and would be nice to be able to use any format, but of course that would add complexity.

this seems like a situation where modular design would be very useful, abstracting the automagic keyboard entry system from what it works with so that others could implement it as well, if there aren't already available apps.

there are auto-typing android apps for "keepass" and this one for "pwsafe" (with added otp support) so there is likely to be one for "pass" if you look around.

(although i notice apple desktop and mobile users have https://github.com/mmcguill/Strongbox which supports both keepass and pwsafe)

**Comment by tejado** [comment]
@jmichael2497 are you interessted to contribute to Authorizer to make it more modular and to support also pass and keepass?

**Comment by jmichael2497** [comment]
currently my contributions to projects are in detailed bug reports and trying to help make sure devs are aware of each other and similar projects for collaboration and inspiration rather than reinventing wheels.

in that spirit, i happened to notice another f-droid listed open source project of relevance to this thread:

* https://github.com/zeapo/Android-Password-Store

provides "pass" support (with the help of https://github.com/open-keychain/open-keychain).

**Comment by tejado** [comment]
Currently I don't have any plans to integrate this. Contributions are highly welcome!
